### ISSUE TITLE
examples-common project is added when BGFX_BUILD_EXAMPLES option is turned off.

### ISSUE THREAD

**Issue by JimmyLord** [bkaradzic/bgfx.cmake-archived#224]
When adding bgfx to a new cmake project using the following:

```
option(BGFX_BUILD_TOOLS "" OFF)
option(BGFX_BUILD_EXAMPLES "" OFF)
option(BGFX_BUILD_TESTS "" OFF)
option(BGFX_INSTALL "" OFF)
option(BGFX_CUSTOM_TARGETS "" OFF)
add_subdirectory("Libraries/bgfx.cmake")
```

The examples-common project is still added to my solution.

This can be fixed by wrapping `add_example( common ... ... ... )` in a `if(BGFX_BUILD_EXAMPLES)` block in the `examples.cmake` file.

**Comment by bwrsandman** [comment]
It's not only examples that link with examples common. Shaderc is in tools as one example.
