### ISSUE TITLE
Is it possible to define WL_EGL_PLATFORM through bgfx.cmake?

### ISSUE THREAD

**Issue by Gaspard--** [bkaradzic/bgfx.cmake-archived#232]
Hello !

Is it possible to define WL_EGL_PLATFORM through bgfx.cmake?

I tried looking at the source, yet I can't find any reference to this define.
Maybe I missed a way to set it directly?

If it's currently not possible it makes using bgfx.cmake on linux a little complicated.
I'm also not an expert at cmake so I may be approaching this the wrong way.

**Comment by Gaspard--** [comment]
I worked around the issue used this snippet for anyone having a similar issue:
```cmake
target_compile_definitions(bgfx PRIVATE WL_EGL_PLATFORM)
```

**Comment by bwrsandman** [comment]
I guess we could add an option called `BGFX_CONFIG_WITH_WAYLAND` for this in the cmake that optionally sets that define.
